[package]
name = "board_game_ai"
version = "0.1.0"
authors = ["William Ganucheau <williamg.online@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
chess = "3.1.1"

